version: "3.9"

services:
  postgres:
    image: postgres:16
    networks: 
      - local_todo_network
    container_name: todolist_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_TODO_DATABASE}
      POSTGRES_USER: ${DB_TODO_USER}
      POSTGRES_PASSWORD: ${DB_TODO_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: todolist_pgadmin
    networks: 
      - local_todo_network
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  todo_backend:
    build: ./backendTodoList
    restart: always
    networks: 
      - local_todo_network
    ports:
      - 8140:3000
    environment:
      CONTAINER_NAME: todo_backend
      PORT: 3000
      DB_HOST: postgres
      DB_DATABASE: ${DB_TODO_DATABASE}
      DB_PASSWORD: ${DB_TODO_PASSWORD}
      DB_USER: ${DB_TODO_USER}
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      # http (без TLS)
      - "traefik.http.routers.todo_http.rule=PathPrefix(`/api-todo`)"
      - "traefik.http.routers.todo_http.entrypoints=web"
      - "traefik.http.routers.todo_http.service=todo"
      - "traefik.http.routers.todo_http.middlewares=auth_sso@docker"
      # https (с TLS)
      - "traefik.http.routers.todo_https.rule=PathPrefix(`/api-todo`)"
      - "traefik.http.routers.todo_https.entrypoints=websecure"
      - "traefik.http.routers.todo_https.tls=true"
      - "traefik.http.routers.todo_https.service=todo"
      - "traefik.http.routers.todo_https.middlewares=auth_sso@docker"
      # общий сервис
      - "traefik.http.services.todo.loadbalancer.server.port=3000"
  
  todo_frontend:
    container_name: todo_frontend
    networks: 
      - local_todo_network
    build:
      context: frontend        
      dockerfile: Dockerfile
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.todo_frontend_strip.stripprefix.prefixes=/todo"
      # http
      - "traefik.http.routers.todo_frontend_http.rule=PathPrefix(`/todo`)"
      - "traefik.http.routers.todo_frontend_http.entrypoints=web"
      - "traefik.http.routers.todo_frontend_http.service=todo_frontend"
      - "traefik.http.routers.todo_frontend_http.priority=1"
      - "traefik.http.routers.todo_frontend_http.middlewares=todo_frontend_strip"

      # https
      - "traefik.http.routers.todo_frontend_https.rule=PathPrefix(`/todo`)"
      - "traefik.http.routers.todo_frontend_https.entrypoints=websecure"
      - "traefik.http.routers.todo_frontend_https.tls=true"
      - "traefik.http.routers.todo_frontend_https.service=todo_frontend"
      - "traefik.http.routers.todo_frontend_https.priority=1"
      - "traefik.http.routers.todo_frontend_https.middlewares=todo_frontend_strip"
      # общий сервис
      - "traefik.http.services.todo_frontend.loadbalancer.server.port=80"
    depends_on:
      auth_service:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pgdata:

networks:
  local_todo_network:
    name: ${NETWORK_NAME}
    external: true